Feature/new iban countrycodes
janv8000/IbanValidation pull request #2
Opened 2017-05-23 14:13 UTC by PaddoSwam

Added new iban country codes and additional unit tests for proofing their validity.

This also contains a fix for issue #1 Costa Rican IBAN now checking against a length of 22.

New CountryCodes:

```
	{"AO", 25 },	//	Angola
	{"BF", 27 },	//	Burkina Faso
	{"BI", 16 },	//	Burundi
	{"BJ", 28 },	//	Benin
	{"BY", 28 },	//	Belarus
	{"CI", 28 },	//	Ivory Coast
	{"CM", 27 },	//	Cameroon
	{"CV", 25 },	//	Cape Verse
	{"DZ", 24 },	//	Algeria
	{"IM", 22 },	//	Isle of Man
	{"IQ", 23 },	//	Iraq
	{"IR", 26 },	//	Ireland
	{"JO", 30 },	//	Jordan
	{"LC", 32 },	//	St Lucia
	{"MG", 27 },	//	Madagascar
	{"ML", 28 },	//	Mali
	{"MZ", 25 },	//	Mozambique
	{"QA", 29 },	//	Qatar
	{"SC", 31 },	//	Seychelles
	{"SN", 28 },	//	Senegal
	{"ST", 25 },	//	São Tomé and Príncipe
	{"SV", 28 },	//	El Salvador
	{"TL", 23 },	//	East-Timor
	{"UA", 29 },	//	Ukraine
	{"XK", 20 }	//	Kosovo
```

2017-06-02 13:00 UTC, janv8000 commented on IbanValidation.Web/IbanAttribute.cs
> +using IbanValidation;
Unused using

2017-06-02 13:00 UTC, janv8000 commented on IbanValidation/IbanValidation.csproj
> +    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
Is there a reason why you upgraded the target framework version? I'd like to keep it as low as possible...

2017-06-02 13:24 UTC, PaddoSwam commented on IbanValidation/IbanValidation.csproj
> +    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
Defintely not, keep it low! 👍

2017-06-02 13:38 UTC, PaddoSwam commented
Updated :)

2017-06-21 14:38 UTC, PaddoSwam commented
@janv8000 it's been a while, is it good to merge? 😄

2017-06-22 07:01 UTC, janv8000 requested changes
Excellent work, if you could just change the appveyor settings I'll merge the PR and get a new release on Nuget

2017-06-22 07:01 UTC, janv8000 commented on README.md
> +[![Build status](https://ci.appveyor.com/api/projects/status/2vn195i624lpd8cw/branch/feature/new-iban-countrycodes?svg=true)](https://ci.appveyor.com/project/PaddoSwam/ibanvalidation/branch/feature/n
Could you change this to 
```
[![Build status](https://ci.appveyor.com/api/projects/status/lweml30irx0ad7vs/branch/master?svg=true)](https://ci.appveyor.com/project/janv8000/ibanvalidation/branch/master)
```

2017-06-22 09:33 UTC, PaddoSwam commented
Done! 👍

2017-06-22 14:40 UTC, janv8000 approved these changes

2017-06-22 14:41 UTC, merged